services:
  # Servicio para la aplicación FastAPI
  fastapi:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      # command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 180
  
networks:
  app-network:
    driver: bridge