name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Desencadena el flujo solo en cambios en la rama main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del código fuente
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Paso 3: Construir y etiquetar la imagen Docker
    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./api-mercadolibre  # Ruta donde está tu Dockerfile
        file: ./api-mercadolibre/Dockerfile
        push: true  # Subir la imagen a Docker Hub
        tags: ${{ secrets.DOCKER_USERNAME }}/smart-price:latest
